module.exports.EuropeCities = {
    LISBOA: { name: "Lisboa" },
    MADRID: { name: "Madrid" },
    CADIZ: { name: "Cadiz" },
    BARCELONA: { name: "Barcelona" },
    PAMPLONA: { name: "Pamplona" },
    MARSEILLE: { name: "Marseille" },
    PARIS: { name: "Paris" },
    ZURICH: { name: "Zürich" },
    ROMA: { name: "Roma" },
    VENEZIA: { name: "Venezia" },
    BRINDISI: { name: "Brindisi" },
    PALERMO: { name: "Palermo" },
    ZAGRAB: { name: "Zagrab" },
    SARAJEVO: { name: "Sarajevo" },
    BUDAPEST: { name: "Budapest" },
    ATHINA: { name: "Athina" },
    SOFIA: { name: "Sofia" },
    BUCURESTI: { name: "Bucuresti" },
    SMYRNA: { name: "Smyrna" },
    CONSTANTINOPLE: { name: "Constantinople" },
    SEVASTOPOL: { name: "Sevastopol" },
    ANGORA: { name: "Angora" },
    ERZURUM: { name: "Erzurum" },
    SOCHI: { name: "Sochi" },
    ROSTOV: { name: "Rostov" },
    KHARKOV: { name: "Kharkov" },
    MOSKVA: { name: "Moskva" },
    SMOLENSK: { name: "Smolensk" },
    PETROGRAD: { name: "Petrograd" },
    KYIV: { name: "Kyïv" },
    WILNO: { name: "Wilno" },
    RIGA: { name: "Riga" },
    WARSZAWA: { name: "Warszawa" },
    DANZIG: { name: "Danzig" },
    STOCKHOLM: { name: "Stockholm" },
    KOBENHAVN: { name: "Kobenhavn" },
    BERLIN: { name: "Berlin" },
    WIEN: {name: "Wien"},
    MUNCHEN: {name: "München"},
    FRANKFURT: {name: "Frankfurt"},
    ESSEN: {name: "Essen"},
    AMSTERDAM: {name: "Amsterdam"},
    BRUXELLES: {name: "Bruxelles"},
    DIEPPE: {name: "Dieppe"},
    LONDON: {name: "London"},
    EDINBURGH: {name: "Edinburgh"},
    BREST: {name: "Brest"}
}