module.exports.FranceCities = {
  ESPAGNE: { name: 'ESPAGNE' },
  ITALIE: { name: 'ITALIE' },
  SUISSE: { name: 'SUISSE' },
  ALLEMAGNE: { name: 'ALLEMAGNE' },
  BELGIQUE: { name: 'BELGIQUE' },
  CORSE: { name: 'CORSE' },
  CHERBOURG: { name: 'Cherbourg' },
  CALAIS: { name: 'Calais' },
  SAINT_MALO: { name: 'Saint-Malo' },
  LE_HAVRE: { name: 'Le Havre' },
  ROUEN: { name: 'Rouen' },
  AMIENS: { name: 'Amiens' },
  LILLE: { name: 'Lille' },
  LORIENT: { name: 'Lorient' },
  RENNES: { name: 'Rennes' },
  LE_MANS: { name: 'Le Mans' },
  REIMS: { name: 'Reims' },
  METZ: { name: 'Metz' },
  NANTES: { name: 'Nantes' },
  ANGERS: { name: 'Angers' },
  TOURS: { name: 'Tours' },
  ORLEANS: { name: 'Orléans' },
  NANCY: { name: 'Nancy' },
  STRASBOURG: { name: 'Strasbourg' },
  LA_ROCHELLE: { name: 'La Rochelle' },
  POITIERS: { name: 'Poitiers' },
  BOURGES: { name: 'Bourges' },
  DIJON: { name: 'Dijon' },
  BESANCON: { name: 'Besançon' },
  MULHOUSE: { name: 'Mulhouse' },
  BORDEAUX: { name: 'Bordeaux' },
  LIMOGES: { name: 'Limoges' },
  CLERMONT_FERRAND: { name: 'Clermont-Ferrand' },
  LYON: { name: 'Lyon' },
  BRIVE_LA_GAILLARDE: { name: 'Brive-la-Gaillarde' },
  BAYONNE: { name: 'Bayonne' },
  PAU: { name: 'Pau' },
  TOULOUSE: { name: 'Toulouse' },
  RODEZ: { name: 'Rodez' },
  GRENOBLE: { name: 'Grenoble' },
  AVIGNON: { name: 'Avignon' },
  BRIANCON: { name: 'Briançon' },
  MONTPELLIER: { name: 'Montpellier' },
  PERPIGNAN: { name: 'Perpignan' },
  NICE: { name: 'Nice' },
  MARSEILLE: { name: 'Marseille' },
  PARIS: { name: 'Paris' },
  BREST: { name: 'Brest' },
};
