module.exports.SwitzerlandCities = {
    FRANCE: { name: "FRANCE" },
    ITALIA: { name: "ITALIA" },
    OSTERREICH: { name: "ÖSTERREICH" },
    DEUTSCHLAND: { name: "DEUTSCHLAND" },
    GENEVE: { name: "Genève" },
    LAUSANNE: { name: "Lausanne" },
    YVERDON: { name: "Yverdon" },
    LA_CHAUX_DE_FONDS: { name: "La Chaux-de-Fonds" },
    DELEMONT: { name: "Delémont" },
    NEUCHATEL: { name: "Neuchâtel" },
    FRIBOURG: { name: "Fribourg" },
    MARTIGNY: { name: "Martigny" },
    SION: { name: "Sion" },
    BRIG: { name: "Brig" },
    INTERLAKEN: { name: "Interlaken" },
    BERN: { name: "Bern" },
    SOLOTHURN: { name: "Solothurn" },
    BASEL: { name: "Basel" },
    OLTEN: { name: "Olten" },
    BADEN: { name: "Baden" },
    ZURICH: { name: "Zürich" },
    ZUG: { name: "Zug" },
    LUZERN: { name: "Luzern" },
    SCHWYZ: { name: "Schwyz" },
    WASSEN: { name: "Wassen" },
    LOCARNO: { name: "Locarno" },
    PFAFFIKON: { name: "Pfäffikon" },
    WINTERTHUR: { name: "Winterthur" },
    SCHAFFHAUSEN: { name: "Schaffhausen" },
    LUGANO: { name: "Lugano" },
    BELLINZONA: { name: "Bellinzona" },
    BRUSIO: { name: "Brusio" },
    DAVOS: { name: "Davos" },
    CHUR: { name: "Chur" },
    SARGANS: { name: "Sargans" },
    VADUZ: { name: "Vaduz" },
    ST_GALLEN: { name: "St. Gallen" },
    KREUZLINGEN: { name: "Kreuzlingen" },
}