import { Types } from "./types"
import { WorldCities } from "./world-cities"
import { GreatLakesCities } from "./great-lakes-cities"

let world = [
    {id: 1, type: Types.ROUTE, cities: [WorldCities.MEXICO, WorldCities.BEIJING], points: 13},
    {id: 2, type: Types.ROUTE, cities: [WorldCities.EDINBURGH, WorldCities.SYDNEY], points: 25},
    {id: 3, type: Types.ROUTE, cities: [WorldCities.LAGOS, WorldCities.TEHRAN], points: 10},
    {id: 4, type: Types.ROUTE, cities: [WorldCities.ATHINA, WorldCities.MANILA], points: 14},
    {id: 5, type: Types.ROUTE, cities: [WorldCities.VALPARAISO, WorldCities.RIO_DE_JANEIRO], points: 6},
    {id: 6, type: Types.ROUTE, cities: [WorldCities.CAPE_TOWN, WorldCities.JAKARTA], points: 13},
    {id: 7, type: Types.ROUTE, cities: [WorldCities.RIO_DE_JANEIRO, WorldCities.PERTH], points: 17},
    {id: 8, type: Types.ROUTE, cities: [WorldCities.MOSKVA, WorldCities.TOAMASINA], points: 11},
    {id: 9, type: Types.ROUTE, cities: [WorldCities.HAMBURG, WorldCities.BEIJING], points: 13},
    {id: 10, type: Types.ROUTE, cities: [WorldCities.RIO_DE_JANEIRO, WorldCities.DAR_ES_SALAAM], points: 11},
    {id: 11, type: Types.ROUTE, cities: [WorldCities.MOSKVA, WorldCities.HONG_KONG], points: 13},
    {id: 12, type: Types.ROUTE, cities: [WorldCities.BUENOS_AIRES, WorldCities.MANILA], points: 17},
    {id: 13, type: Types.ROUTE, cities: [WorldCities.NEW_YORK, WorldCities.CAPE_TOWN], points: 19},
    {id: 14, type: Types.ROUTE, cities: [WorldCities.MIAMI, WorldCities.MOSKVA], points: 13},
    {id: 15, type: Types.ROUTE, cities: [WorldCities.NEW_YORK, WorldCities.MARSEILLE], points: 10},
    {id: 16, type: Types.ROUTE, cities: [WorldCities.AL_QAHIRA, WorldCities.SYDNEY], points: 19},
    {id: 17, type: Types.ROUTE, cities: [WorldCities.BUENOS_AIRES, WorldCities.SYDNEY], points: 13},
    {id: 18, type: Types.ROUTE, cities: [WorldCities.CASABLANCA, WorldCities.YAKUTSK], points: 16},
    {id: 19, type: Types.ROUTE, cities: [WorldCities.EDINBURGH, WorldCities.LUANDA], points: 10},
    {id: 20, type: Types.ROUTE, cities: [WorldCities.LOS_ANGELES, WorldCities.HAMBURG], points: 14},
    {id: 21, type: Types.ROUTE, cities: [WorldCities.LOS_ANGELES, WorldCities.DAR_ES_SALAAM], points: 17},
    {id: 22, type: Types.ROUTE, cities: [WorldCities.EDINBURGH, WorldCities.HONG_KONG], points: 17},
    {id: 23, type: Types.ROUTE, cities: [WorldCities.VANCOUVER, WorldCities.EDINBURGH], points: 13},
    {id: 24, type: Types.ROUTE, cities: [WorldCities.WINNIPEG, WorldCities.PERTH], points: 14},
    {id: 25, type: Types.ROUTE, cities: [WorldCities.MEXICO, WorldCities.NEW_YORK], points: 11},
    {id: 26, type: Types.ROUTE, cities: [WorldCities.HONG_KONG, WorldCities.JAKARTA], points: 5},
    {id: 27, type: Types.ROUTE, cities: [WorldCities.MARSEILLE, WorldCities.CHRISTCHURCH], points: 23},
    {id: 28, type: Types.ROUTE, cities: [WorldCities.MOSKVA, WorldCities.PETROPAVLOVSK], points: 15},
    {id: 29, type: Types.ROUTE, cities: [WorldCities.RIO_DE_JANEIRO, WorldCities.TOKYO], points: 20},
    {id: 30, type: Types.ROUTE, cities: [WorldCities.HAMBURG, WorldCities.DAR_ES_SALAAM], points: 8},
    {id: 31, type: Types.ROUTE, cities: [WorldCities.DJIBOUTI, WorldCities.LAHORE], points: 7},
    {id: 32, type: Types.ROUTE, cities: [WorldCities.EDINBURGH, WorldCities.TOKYO], points: 22},
    {id: 33, type: Types.ROUTE, cities: [WorldCities.LOS_ANGELES, WorldCities.RIO_DE_JANEIRO], points: 15},
    {id: 34, type: Types.ROUTE, cities: [WorldCities.LAGOS, WorldCities.HONG_KONG], points: 14},
    {id: 35, type: Types.ROUTE, cities: [WorldCities.BUENOS_AIRES, WorldCities.MARSEILLE], points: 18},
    {id: 36, type: Types.ROUTE, cities: [WorldCities.MEXICO, WorldCities.BEIJING], points: 13},
    {id: 37, type: Types.ROUTE, cities: [WorldCities.CASABLANCA, WorldCities.HONOLULU], points: 16},
    {id: 38, type: Types.ROUTE, cities: [WorldCities.LIMA, WorldCities.JAKARTA], points: 14},
    {id: 39, type: Types.ROUTE, cities: [WorldCities.MARSEILLE, WorldCities.JAKARTA], points: 18},
    {id: 40, type: Types.ROUTE, cities: [WorldCities.RIO_DE_JANEIRO, WorldCities.HAMBURG], points: 13},
    {id: 41, type: Types.ROUTE, cities: [WorldCities.MARSEILLE, WorldCities.BEIJING], points: 14},
    {id: 42, type: Types.ROUTE, cities: [WorldCities.LOS_ANGELES, WorldCities.JAKARTA], points: 11},
    {id: 43, type: Types.ROUTE, cities: [WorldCities.NEW_YORK, WorldCities.TOKYO], points: 15},
    {id: 44, type: Types.ROUTE, cities: [WorldCities.NEW_YORK, WorldCities.SYDNEY], points: 17},
    {id: 45, type: Types.ROUTE, cities: [WorldCities.TOKYO, WorldCities.SYDNEY], points: 11},
    {id: 46, type: Types.ROUTE, cities: [WorldCities.JAKARTA, WorldCities.SYDNEY], points: 7},
    {id: 47, type: Types.ROUTE, cities: [WorldCities.BANGKOK, WorldCities.TOKYO], points: 6},
    {id: 48, type: Types.ROUTE, cities: [WorldCities.REYKJAVIK, WorldCities.MUMBAI], points: 13},
    {id: 49, type: Types.ROUTE, cities: [WorldCities.DAR_ES_SALAAM, WorldCities.TOKYO], points: 15},
    {id: 50, type: Types.ROUTE, cities: [WorldCities.MEXICO, WorldCities.MUMBAI], points: 15},
    {id: 51, type: Types.ROUTE, cities: [WorldCities.CARACAS, WorldCities.AL_QAHIRA], points: 13},
    {id: 52, type: Types.ROUTE, cities: [WorldCities.NEW_YORK, WorldCities.MUMBAI], points: 19},
    {id: 53, type: Types.ROUTE, cities: [WorldCities.MUMBAI, WorldCities.BEIJING], points: 6},
    {id: 54, type: Types.ROUTE, cities: [WorldCities.CARACAS, WorldCities.ATHINA], points: 12},
    {id: 55, type: Types.ROUTE, cities: [WorldCities.MIAMI, WorldCities.BUENOS_AIRES], points: 9},
    {id: 56, type: Types.ROUTE, cities: [WorldCities.VANCOUVER, WorldCities.MIAMI], points: 9},
    {id: 57, type: Types.ROUTE, cities: [WorldCities.MARSEILLE, WorldCities.AL_QAHIRA], points: 5},
    {id: 58, type: Types.ROUTE, cities: [WorldCities.NOVOSIBIRSK, WorldCities.DARWIN], points: 13},
    {id: 59, type: Types.TOUR, cities: [WorldCities.MURMANSK, WorldCities.TIKSI, WorldCities.NOVOSIBIRSK, WorldCities.YAKUTSK, WorldCities.PETROPAVLOVSK], points: 30, points_unorderded: 20, points_failed: -36},
    {id: 60, type: Types.TOUR, cities: [WorldCities.ANCHORAGE, WorldCities.CAMBRIDGE_BAY, WorldCities.REYKJAVIK, WorldCities.MURMANSK, WorldCities.TIKSI], points: 34, points_unorderded: 23, points_failed: -40},
    {id: 61, type: Types.TOUR, cities: [WorldCities.MANILA, WorldCities.HONOLULU, WorldCities.PORT_MORESBY, WorldCities.DARWIN], points: 13, points_unorderded: 9, points_failed: -19},
    {id: 62, type: Types.TOUR, cities: [WorldCities.ANCHORAGE, WorldCities.VANCOUVER, WorldCities.WINNIPEG, WorldCities.CAMBRIDGE_BAY], points: 18, points_unorderded: 12, points_failed: -24},
    {id: 63, type: Types.TOUR, cities: [WorldCities.TEHRAN, WorldCities.LAHORE, WorldCities.MUMBAI, WorldCities.BANGKOK], points: 13, points_unorderded: 9, points_failed: -19},
    {id: 64, type: Types.TOUR, cities: [WorldCities.CASABLANCA, WorldCities.AL_QAHIRA, WorldCities.TEHRAN], points: 9, points_unorderded: 6, points_failed: -15},
    {id: 65, type: Types.TOUR, cities: [WorldCities.LAGOS, WorldCities.LUANDA, WorldCities.DAR_ES_SALAAM, WorldCities.DJIBOUTI], points: 9, points_unorderded: 6, points_failed: -15},
    {id: 66, type: Types.TOUR, cities: [WorldCities.MEXICO, WorldCities.CARACAS, WorldCities.LIMA, WorldCities.VALPARAISO], points: 15, points_unorderded: 10, points_failed: -21},
]

let greatlakes = [
    {id: 1, cities: [GreatLakesCities.SOUTH_BEND, GreatLakesCities.SYRACUSE], points: 9},
    {id: 2, cities: [GreatLakesCities.DULUTH, GreatLakesCities.NEW_YORK], points: 24},
    {id: 3, cities: [GreatLakesCities.MARQUETTE, GreatLakesCities.BUFFALO], points: 8},
    {id: 4, cities: [GreatLakesCities.PARRY_SOUND, GreatLakesCities.ROUYN_NORANDA], points: 6},
    {id: 5, cities: [GreatLakesCities.CLEVELAND, GreatLakesCities.TORONTO], points: 4},
    {id: 6, cities: [GreatLakesCities.MILWAUKEE, GreatLakesCities.MARQUETTE], points: 8},
    {id: 7, cities: [GreatLakesCities.MADISON, GreatLakesCities.PORT_ELGIN], points: 10},
    {id: 8, cities: [GreatLakesCities.MILWAUKEE, GreatLakesCities.PARRY_SOUND], points: 8},
    {id: 9, cities: [GreatLakesCities.WAUSAU, GreatLakesCities.SUDBURY], points: 10},
    {id: 10, cities: [GreatLakesCities.TOLEDO, GreatLakesCities.SCRANTON], points: 8},
    {id: 11, cities: [GreatLakesCities.EAU_CLAIRE, GreatLakesCities.GREEN_BAY], points: 3},
    {id: 12, cities: [GreatLakesCities.GREEN_BAY, GreatLakesCities.TORONTO], points: 9},
    {id: 13, cities: [GreatLakesCities.CEDAR_RAPIDS, GreatLakesCities.ALBANY], points: 16},
    {id: 14, cities: [GreatLakesCities.BAY_CITY, GreatLakesCities.SCRANTON], points: 9},
    {id: 15, cities: [GreatLakesCities.THUNDER_BAY, GreatLakesCities.TORONTO], points: 9},
    {id: 16, cities: [GreatLakesCities.DULUTH, GreatLakesCities.CHICAGO], points: 10},
    {id: 17, cities: [GreatLakesCities.GREEN_BAY, GreatLakesCities.TIMMINS], points: 13},
    {id: 18, cities: [GreatLakesCities.TORONTO, GreatLakesCities.OTTAWA], points: 5},
    {id: 19, cities: [GreatLakesCities.DULUTH, GreatLakesCities.ROUYN_NORANDA], points: 14},
    {id: 20, cities: [GreatLakesCities.CLEVELAND, GreatLakesCities.OTTAWA], points: 7},
    {id: 21, cities: [GreatLakesCities.MUSKEGON, GreatLakesCities.BUFFALO], points: 9},
    {id: 22, cities: [GreatLakesCities.BUFFALO, GreatLakesCities.ALBANY], points: 4},
    {id: 23, cities: [GreatLakesCities.CEDAR_RAPIDS, GreatLakesCities.SAULT_STE_MARIE], points: 10},
    {id: 24, cities: [GreatLakesCities.CHICAGO, GreatLakesCities.DETROIT], points: 6},
    {id: 25, cities: [GreatLakesCities.DULUTH, GreatLakesCities.TRAVERSE_CITY], points: 7},
    {id: 26, cities: [GreatLakesCities.THUNDER_BAY, GreatLakesCities.OTTAWA], points: 17},
    {id: 27, cities: [GreatLakesCities.CHICAGO, GreatLakesCities.TORONTO], points: 11},
    {id: 28, cities: [GreatLakesCities.CEDAR_RAPIDS, GreatLakesCities.CLEVELAND], points: 11},
    {id: 29, cities: [GreatLakesCities.SOUTH_BAYMOUTH, GreatLakesCities.DETROIT], points: 4},
    {id: 30, cities: [GreatLakesCities.SUDBURY, GreatLakesCities.NEW_YORK], points: 12},
    {id: 31, cities: [GreatLakesCities.MILWAUKEE, GreatLakesCities.ERIE], points: 7},
    {id: 32, cities: [GreatLakesCities.MADISON, GreatLakesCities.OTTAWA], points: 18},
    {id: 33, cities: [GreatLakesCities.PORT_ELGIN, GreatLakesCities.KINGSTON], points: 5},
    {id: 34, cities: [GreatLakesCities.TRAVERSE_CITY, GreatLakesCities.TOLEDO], points: 6},
    {id: 35, cities: [GreatLakesCities.MARATHON, GreatLakesCities.SOUTH_BEND], points: 11},
    {id: 36, cities: [GreatLakesCities.CHICAGO, GreatLakesCities.NEW_YORK], points: 15},
    {id: 37, cities: [GreatLakesCities.SAULT_STE_MARIE, GreatLakesCities.SYRACUSE], points: 8},
    {id: 38, cities: [GreatLakesCities.SAULT_STE_MARIE, GreatLakesCities.SUDBURY], points: 4},
    {id: 39, cities: [GreatLakesCities.SAULT_STE_MARIE, GreatLakesCities.MONTREAL], points: 13},
    {id: 40, cities: [GreatLakesCities.DULUTH, GreatLakesCities.DETROIT], points: 12},
    {id: 41, cities: [GreatLakesCities.GREEN_BAY, GreatLakesCities.CHICAGO], points: 5},
    {id: 42, cities: [GreatLakesCities.SYRACUSE, GreatLakesCities.MONTREAL], points: 5},
    {id: 43, cities: [GreatLakesCities.CHICAGO, GreatLakesCities.MONTREAL], points: 16},
    {id: 44, cities: [GreatLakesCities.EAU_CLAIRE, GreatLakesCities.TOLEDO], points: 12},
    {id: 45, cities: [GreatLakesCities.MUSKEGON, GreatLakesCities.BAY_CITY], points: 6},
    {id: 46, cities: [GreatLakesCities.MARATHON, GreatLakesCities.CLEVELAND], points: 10},
    {id: 47, cities: [GreatLakesCities.DETROIT, GreatLakesCities.MONTREAL], points: 11},
    {id: 48, cities: [GreatLakesCities.DETROIT, GreatLakesCities.NEW_YORK], points: 12},
    {id: 49, cities: [GreatLakesCities.MONTREAL, GreatLakesCities.NEW_YORK], points: 9},
    {id: 50, cities: [GreatLakesCities.CEDAR_RAPIDS, GreatLakesCities.WAUSAU], points: 7},
    {id: 51, cities: [GreatLakesCities.CHICAGO, GreatLakesCities.TIMMINS], points: 15},
    {id: 52, cities: [GreatLakesCities.MARQUETTE, GreatLakesCities.ALBANY], points: 10},
    {id: 53, cities: [GreatLakesCities.ERIE, GreatLakesCities.KINGSTON], points: 4},
    {id: 54, cities: [GreatLakesCities.DULUTH, GreatLakesCities.MONTREAL], points: 19},
    {id: 55, cities: [GreatLakesCities.SYRACUSE, GreatLakesCities.NEW_YORK], points: 5}
]

export const Tickets = {
    World: world,
    GreatLakes: greatlakes
};