import { Types } from "./types"
import { Games } from "./games"
import { WorldCities } from "./world-cities"
import { GreatLakesCities } from "./great-lakes-cities"
import { EuropeCities } from "./europe-cities"

let world = [
    {id: 1, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.MEXICO, WorldCities.BEIJING], points: 13},
    {id: 2, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.EDINBURGH, WorldCities.SYDNEY], points: 25},
    {id: 3, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.LAGOS, WorldCities.TEHRAN], points: 10},
    {id: 4, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.ATHINA, WorldCities.MANILA], points: 14},
    {id: 5, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.VALPARAISO, WorldCities.RIO_DE_JANEIRO], points: 6},
    {id: 6, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.CAPE_TOWN, WorldCities.JAKARTA], points: 13},
    {id: 7, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.RIO_DE_JANEIRO, WorldCities.PERTH], points: 17},
    {id: 8, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.MOSKVA, WorldCities.TOAMASINA], points: 11},
    {id: 9, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.HAMBURG, WorldCities.BEIJING], points: 13},
    {id: 10, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.RIO_DE_JANEIRO, WorldCities.DAR_ES_SALAAM], points: 11},
    {id: 11, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.MOSKVA, WorldCities.HONG_KONG], points: 13},
    {id: 12, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.BUENOS_AIRES, WorldCities.MANILA], points: 17},
    {id: 13, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.NEW_YORK, WorldCities.CAPE_TOWN], points: 19},
    {id: 14, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.MIAMI, WorldCities.MOSKVA], points: 13},
    {id: 15, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.NEW_YORK, WorldCities.MARSEILLE], points: 10},
    {id: 16, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.AL_QAHIRA, WorldCities.SYDNEY], points: 19},
    {id: 17, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.BUENOS_AIRES, WorldCities.SYDNEY], points: 13},
    {id: 18, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.CASABLANCA, WorldCities.YAKUTSK], points: 16},
    {id: 19, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.EDINBURGH, WorldCities.LUANDA], points: 10},
    {id: 20, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.LOS_ANGELES, WorldCities.HAMBURG], points: 14},
    {id: 21, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.LOS_ANGELES, WorldCities.DAR_ES_SALAAM], points: 17},
    {id: 22, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.EDINBURGH, WorldCities.HONG_KONG], points: 17},
    {id: 23, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.VANCOUVER, WorldCities.EDINBURGH], points: 13},
    {id: 24, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.WINNIPEG, WorldCities.PERTH], points: 14},
    {id: 25, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.MEXICO, WorldCities.NEW_YORK], points: 11},
    {id: 26, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.HONG_KONG, WorldCities.JAKARTA], points: 5},
    {id: 27, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.MARSEILLE, WorldCities.CHRISTCHURCH], points: 23},
    {id: 28, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.MOSKVA, WorldCities.PETROPAVLOVSK], points: 15},
    {id: 29, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.RIO_DE_JANEIRO, WorldCities.TOKYO], points: 20},
    {id: 30, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.HAMBURG, WorldCities.DAR_ES_SALAAM], points: 8},
    {id: 31, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.DJIBOUTI, WorldCities.LAHORE], points: 7},
    {id: 32, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.EDINBURGH, WorldCities.TOKYO], points: 22},
    {id: 33, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.LOS_ANGELES, WorldCities.RIO_DE_JANEIRO], points: 15},
    {id: 34, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.LAGOS, WorldCities.HONG_KONG], points: 14},
    {id: 35, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.BUENOS_AIRES, WorldCities.MARSEILLE], points: 18},
    {id: 37, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.CASABLANCA, WorldCities.HONOLULU], points: 16},
    {id: 38, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.LIMA, WorldCities.JAKARTA], points: 14},
    {id: 39, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.MARSEILLE, WorldCities.JAKARTA], points: 18},
    {id: 40, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.RIO_DE_JANEIRO, WorldCities.HAMBURG], points: 13},
    {id: 41, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.MARSEILLE, WorldCities.BEIJING], points: 14},
    {id: 42, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.LOS_ANGELES, WorldCities.JAKARTA], points: 11},
    {id: 43, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.NEW_YORK, WorldCities.TOKYO], points: 15},
    {id: 44, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.NEW_YORK, WorldCities.SYDNEY], points: 17},
    {id: 45, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.TOKYO, WorldCities.SYDNEY], points: 11},
    {id: 46, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.JAKARTA, WorldCities.SYDNEY], points: 7},
    {id: 47, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.BANGKOK, WorldCities.TOKYO], points: 6},
    {id: 48, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.REYKJAVIK, WorldCities.MUMBAI], points: 13},
    {id: 49, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.DAR_ES_SALAAM, WorldCities.TOKYO], points: 15},
    {id: 50, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.MEXICO, WorldCities.MUMBAI], points: 15},
    {id: 51, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.CARACAS, WorldCities.AL_QAHIRA], points: 13},
    {id: 52, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.NEW_YORK, WorldCities.MUMBAI], points: 19},
    {id: 53, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.MUMBAI, WorldCities.BEIJING], points: 6},
    {id: 54, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.CARACAS, WorldCities.ATHINA], points: 12},
    {id: 55, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.MIAMI, WorldCities.BUENOS_AIRES], points: 9},
    {id: 56, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.VANCOUVER, WorldCities.MIAMI], points: 9},
    {id: 57, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.MARSEILLE, WorldCities.AL_QAHIRA], points: 5},
    {id: 58, game: Games.WORLD, type: Types.ROUTE, cities: [WorldCities.NOVOSIBIRSK, WorldCities.DARWIN], points: 13},
    {id: 59, game: Games.WORLD, type: Types.TOUR, cities: [WorldCities.MURMANSK, WorldCities.TIKSI, WorldCities.NOVOSIBIRSK, WorldCities.YAKUTSK, WorldCities.PETROPAVLOVSK], points: 30, points_unorderded: 20, points_failed: -36},
    {id: 60, game: Games.WORLD, type: Types.TOUR, cities: [WorldCities.ANCHORAGE, WorldCities.CAMBRIDGE_BAY, WorldCities.REYKJAVIK, WorldCities.MURMANSK, WorldCities.TIKSI], points: 34, points_unorderded: 23, points_failed: -40},
    {id: 61, game: Games.WORLD, type: Types.TOUR, cities: [WorldCities.MANILA, WorldCities.HONOLULU, WorldCities.PORT_MORESBY, WorldCities.DARWIN], points: 13, points_unorderded: 9, points_failed: -19},
    {id: 62, game: Games.WORLD, type: Types.TOUR, cities: [WorldCities.ANCHORAGE, WorldCities.VANCOUVER, WorldCities.WINNIPEG, WorldCities.CAMBRIDGE_BAY], points: 18, points_unorderded: 12, points_failed: -24},
    {id: 63, game: Games.WORLD, type: Types.TOUR, cities: [WorldCities.TEHRAN, WorldCities.LAHORE, WorldCities.MUMBAI, WorldCities.BANGKOK], points: 13, points_unorderded: 9, points_failed: -19},
    {id: 64, game: Games.WORLD, type: Types.TOUR, cities: [WorldCities.CASABLANCA, WorldCities.AL_QAHIRA, WorldCities.TEHRAN], points: 9, points_unorderded: 6, points_failed: -15},
    {id: 65, game: Games.WORLD, type: Types.TOUR, cities: [WorldCities.LAGOS, WorldCities.LUANDA, WorldCities.DAR_ES_SALAAM, WorldCities.DJIBOUTI], points: 9, points_unorderded: 6, points_failed: -15},
    {id: 66, game: Games.WORLD, type: Types.TOUR, cities: [WorldCities.MEXICO, WorldCities.CARACAS, WorldCities.LIMA, WorldCities.VALPARAISO], points: 15, points_unorderded: 10, points_failed: -21},
]

let greatlakes = [
    {id: 1, game: Games.GREAT_LAKES, cities: [GreatLakesCities.SOUTH_BEND, GreatLakesCities.SYRACUSE], points: 9},
    {id: 2, game: Games.GREAT_LAKES, cities: [GreatLakesCities.DULUTH, GreatLakesCities.NEW_YORK], points: 24},
    {id: 3, game: Games.GREAT_LAKES, cities: [GreatLakesCities.MARQUETTE, GreatLakesCities.BUFFALO], points: 8},
    {id: 4, game: Games.GREAT_LAKES, cities: [GreatLakesCities.PARRY_SOUND, GreatLakesCities.ROUYN_NORANDA], points: 6},
    {id: 5, game: Games.GREAT_LAKES, cities: [GreatLakesCities.CLEVELAND, GreatLakesCities.TORONTO], points: 4},
    {id: 6, game: Games.GREAT_LAKES, cities: [GreatLakesCities.MILWAUKEE, GreatLakesCities.MARQUETTE], points: 8},
    {id: 7, game: Games.GREAT_LAKES, cities: [GreatLakesCities.MADISON, GreatLakesCities.PORT_ELGIN], points: 10},
    {id: 8, game: Games.GREAT_LAKES, cities: [GreatLakesCities.MILWAUKEE, GreatLakesCities.PARRY_SOUND], points: 8},
    {id: 9, game: Games.GREAT_LAKES, cities: [GreatLakesCities.WAUSAU, GreatLakesCities.SUDBURY], points: 10},
    {id: 10, game: Games.GREAT_LAKES, cities: [GreatLakesCities.TOLEDO, GreatLakesCities.SCRANTON], points: 8},
    {id: 11, game: Games.GREAT_LAKES, cities: [GreatLakesCities.EAU_CLAIRE, GreatLakesCities.GREEN_BAY], points: 3},
    {id: 12, game: Games.GREAT_LAKES, cities: [GreatLakesCities.GREEN_BAY, GreatLakesCities.TORONTO], points: 9},
    {id: 13, game: Games.GREAT_LAKES, cities: [GreatLakesCities.CEDAR_RAPIDS, GreatLakesCities.ALBANY], points: 16},
    {id: 14, game: Games.GREAT_LAKES, cities: [GreatLakesCities.BAY_CITY, GreatLakesCities.SCRANTON], points: 9},
    {id: 15, game: Games.GREAT_LAKES, cities: [GreatLakesCities.THUNDER_BAY, GreatLakesCities.TORONTO], points: 9},
    {id: 16, game: Games.GREAT_LAKES, cities: [GreatLakesCities.DULUTH, GreatLakesCities.CHICAGO], points: 10},
    {id: 17, game: Games.GREAT_LAKES, cities: [GreatLakesCities.GREEN_BAY, GreatLakesCities.TIMMINS], points: 13},
    {id: 18, game: Games.GREAT_LAKES, cities: [GreatLakesCities.TORONTO, GreatLakesCities.OTTAWA], points: 5},
    {id: 19, game: Games.GREAT_LAKES, cities: [GreatLakesCities.DULUTH, GreatLakesCities.ROUYN_NORANDA], points: 14},
    {id: 20, game: Games.GREAT_LAKES, cities: [GreatLakesCities.CLEVELAND, GreatLakesCities.OTTAWA], points: 7},
    {id: 21, game: Games.GREAT_LAKES, cities: [GreatLakesCities.MUSKEGON, GreatLakesCities.BUFFALO], points: 9},
    {id: 22, game: Games.GREAT_LAKES, cities: [GreatLakesCities.BUFFALO, GreatLakesCities.ALBANY], points: 4},
    {id: 23, game: Games.GREAT_LAKES, cities: [GreatLakesCities.CEDAR_RAPIDS, GreatLakesCities.SAULT_STE_MARIE], points: 10},
    {id: 24, game: Games.GREAT_LAKES, cities: [GreatLakesCities.CHICAGO, GreatLakesCities.DETROIT], points: 6},
    {id: 25, game: Games.GREAT_LAKES, cities: [GreatLakesCities.DULUTH, GreatLakesCities.TRAVERSE_CITY], points: 7},
    {id: 26, game: Games.GREAT_LAKES, cities: [GreatLakesCities.THUNDER_BAY, GreatLakesCities.OTTAWA], points: 17},
    {id: 27, game: Games.GREAT_LAKES, cities: [GreatLakesCities.CHICAGO, GreatLakesCities.TORONTO], points: 11},
    {id: 28, game: Games.GREAT_LAKES, cities: [GreatLakesCities.CEDAR_RAPIDS, GreatLakesCities.CLEVELAND], points: 11},
    {id: 29, game: Games.GREAT_LAKES, cities: [GreatLakesCities.SOUTH_BAYMOUTH, GreatLakesCities.DETROIT], points: 4},
    {id: 30, game: Games.GREAT_LAKES, cities: [GreatLakesCities.SUDBURY, GreatLakesCities.NEW_YORK], points: 12},
    {id: 31, game: Games.GREAT_LAKES, cities: [GreatLakesCities.MILWAUKEE, GreatLakesCities.ERIE], points: 7},
    {id: 32, game: Games.GREAT_LAKES, cities: [GreatLakesCities.MADISON, GreatLakesCities.OTTAWA], points: 18},
    {id: 33, game: Games.GREAT_LAKES, cities: [GreatLakesCities.PORT_ELGIN, GreatLakesCities.KINGSTON], points: 5},
    {id: 34, game: Games.GREAT_LAKES, cities: [GreatLakesCities.TRAVERSE_CITY, GreatLakesCities.TOLEDO], points: 6},
    {id: 35, game: Games.GREAT_LAKES, cities: [GreatLakesCities.MARATHON, GreatLakesCities.SOUTH_BEND], points: 11},
    {id: 36, game: Games.GREAT_LAKES, cities: [GreatLakesCities.CHICAGO, GreatLakesCities.NEW_YORK], points: 15},
    {id: 37, game: Games.GREAT_LAKES, cities: [GreatLakesCities.SAULT_STE_MARIE, GreatLakesCities.SYRACUSE], points: 8},
    {id: 38, game: Games.GREAT_LAKES, cities: [GreatLakesCities.SAULT_STE_MARIE, GreatLakesCities.SUDBURY], points: 4},
    {id: 39, game: Games.GREAT_LAKES, cities: [GreatLakesCities.SAULT_STE_MARIE, GreatLakesCities.MONTREAL], points: 13},
    {id: 40, game: Games.GREAT_LAKES, cities: [GreatLakesCities.DULUTH, GreatLakesCities.DETROIT], points: 12},
    {id: 41, game: Games.GREAT_LAKES, cities: [GreatLakesCities.GREEN_BAY, GreatLakesCities.CHICAGO], points: 5},
    {id: 42, game: Games.GREAT_LAKES, cities: [GreatLakesCities.SYRACUSE, GreatLakesCities.MONTREAL], points: 5},
    {id: 43, game: Games.GREAT_LAKES, cities: [GreatLakesCities.CHICAGO, GreatLakesCities.MONTREAL], points: 16},
    {id: 44, game: Games.GREAT_LAKES, cities: [GreatLakesCities.EAU_CLAIRE, GreatLakesCities.TOLEDO], points: 12},
    {id: 45, game: Games.GREAT_LAKES, cities: [GreatLakesCities.MUSKEGON, GreatLakesCities.BAY_CITY], points: 6},
    {id: 46, game: Games.GREAT_LAKES, cities: [GreatLakesCities.MARATHON, GreatLakesCities.CLEVELAND], points: 10},
    {id: 47, game: Games.GREAT_LAKES, cities: [GreatLakesCities.DETROIT, GreatLakesCities.MONTREAL], points: 11},
    {id: 48, game: Games.GREAT_LAKES, cities: [GreatLakesCities.DETROIT, GreatLakesCities.NEW_YORK], points: 12},
    {id: 49, game: Games.GREAT_LAKES, cities: [GreatLakesCities.MONTREAL, GreatLakesCities.NEW_YORK], points: 9},
    {id: 50, game: Games.GREAT_LAKES, cities: [GreatLakesCities.CEDAR_RAPIDS, GreatLakesCities.WAUSAU], points: 7},
    {id: 51, game: Games.GREAT_LAKES, cities: [GreatLakesCities.CHICAGO, GreatLakesCities.TIMMINS], points: 15},
    {id: 52, game: Games.GREAT_LAKES, cities: [GreatLakesCities.MARQUETTE, GreatLakesCities.ALBANY], points: 10},
    {id: 53, game: Games.GREAT_LAKES, cities: [GreatLakesCities.ERIE, GreatLakesCities.KINGSTON], points: 4},
    {id: 54, game: Games.GREAT_LAKES, cities: [GreatLakesCities.DULUTH, GreatLakesCities.MONTREAL], points: 19},
    {id: 55, game: Games.GREAT_LAKES, cities: [GreatLakesCities.SYRACUSE, GreatLakesCities.NEW_YORK], points: 5},
];

let europe = [
    {id:1, game:Games.EUROPE, cities:[EuropeCities.EDINBURGH, EuropeCities.ATHINA], points: 21, long: true},
    {id:2, game:Games.EUROPE, cities:[EuropeCities.CADIZ, EuropeCities.STOCKHOLM], points: 21, long:true },
    {id:3, game:Games.EUROPE, cities:[EuropeCities.KOBENHAVN, EuropeCities.ERZURUM], points: 21, long:true },
    {id:4, game:Games.EUROPE, cities:[EuropeCities.BREST, EuropeCities.PETROGRAD], points: 20, long:true },
    {id:5, game:Games.EUROPE, cities:[EuropeCities.PALERMO, EuropeCities.MOSKVA], points: 20, long:true },
    {id:6, game:Games.EUROPE, cities:[EuropeCities.LISBOA, EuropeCities.DANZIG], points: 20, long:true },
    {id:7, game:Games.EUROPE, cities:[EuropeCities.FRANKFURT, EuropeCities.SMOLENSK], points: 13, long:false },
    {id:8, game:Games.EUROPE, cities:[EuropeCities.BERLIN, EuropeCities.MOSKVA], points: 12, long:false },
    {id:9, game:Games.EUROPE, cities:[EuropeCities.AMSTERDAM, EuropeCities.WILNO], points: 12, long:false },
    {id:10, game:Games.EUROPE, cities:[EuropeCities.ATHINA, EuropeCities.WILNO], points: 11, long:false },
    {id:11, game:Games.EUROPE, cities:[EuropeCities.STOCKHOLM, EuropeCities.WIEN], points: 11, long:false },
    {id:12, game:Games.EUROPE, cities:[EuropeCities.ANGORA, EuropeCities.KHARKOV], points: 10, long:false },
    {id:13, game:Games.EUROPE, cities:[EuropeCities.ESSEN, EuropeCities.KYIV], points: 10, long:false },
    {id:14, game:Games.EUROPE, cities:[EuropeCities.RIGA, EuropeCities.BUCURESTI], points: 10, long:false },
    {id:15, game:Games.EUROPE, cities:[EuropeCities.VENEZIA, EuropeCities.CONSTANTINOPLE], points: 10, long:false },
    {id:16, game:Games.EUROPE, cities:[EuropeCities.LONDON, EuropeCities.WIEN], points: 10, long:false },
    {id:17, game:Games.EUROPE, cities:[EuropeCities.BRUXELLES, EuropeCities.DANZIG], points: 9, long:false },
    {id:18, game:Games.EUROPE, cities:[EuropeCities.BERLIN, EuropeCities.ROMA], points: 9, long:false },
    {id:19, game:Games.EUROPE, cities:[EuropeCities.KYIV, EuropeCities.SOCHI], points: 8, long:false },
    {id:20, game:Games.EUROPE, cities:[EuropeCities.ROMA, EuropeCities.SMYRNA], points: 8, long:false },
    {id:21, game:Games.EUROPE, cities:[EuropeCities.BERLIN, EuropeCities.BUCURESTI], points: 8, long:false },
    {id:22, game:Games.EUROPE, cities:[EuropeCities.SARAJEVO, EuropeCities.SEVASTOPOL], points: 8, long:false },
    {id:23, game:Games.EUROPE, cities:[EuropeCities.SMOLENSK, EuropeCities.ROSTOV], points: 8, long:false },
    {id:24, game:Games.EUROPE, cities:[EuropeCities.BARCELONA, EuropeCities.MUNCHEN], points: 8, long:false },
    {id:25, game:Games.EUROPE, cities:[EuropeCities.BARCELONA, EuropeCities.BRUXELLES], points: 8, long:false },
    {id:26, game:Games.EUROPE, cities:[EuropeCities.MARSEILLE, EuropeCities.ESSEN], points: 8, long:false },
    {id:27, game:Games.EUROPE, cities:[EuropeCities.MADRID, EuropeCities.DIEPPE], points: 8, long:false },
    {id:28, game:Games.EUROPE, cities:[EuropeCities.PALERMO, EuropeCities.CONSTANTINOPLE], points: 8, long:false },
    {id:29, game:Games.EUROPE, cities:[EuropeCities.BREST, EuropeCities.VENEZIA], points: 8, long:false },
    {id:30, game:Games.EUROPE, cities:[EuropeCities.PARIS, EuropeCities.WIEN], points: 8, long:false },
	{id:31, game:Games.EUROPE, cities:[EuropeCities.MADRID, EuropeCities.ZURICH], points: 8, long:false },
	{id:32, game:Games.EUROPE, cities:[EuropeCities.AMSTERDAM, EuropeCities.PAMPLONA], points: 7, long:false },
	{id:33, game:Games.EUROPE, cities:[EuropeCities.EDINBURGH, EuropeCities.PARIS], points: 7, long:false },
	{id:34, game:Games.EUROPE, cities:[EuropeCities.LONDON, EuropeCities.BERLIN], points: 7, long:false },
	{id:35, game:Games.EUROPE, cities:[EuropeCities.PARIS, EuropeCities.ZAGRAB], points: 7, long:false },
	{id:36, game:Games.EUROPE, cities:[EuropeCities.BREST, EuropeCities.MARSEILLE], points: 7, long:false },
	{id:37, game:Games.EUROPE, cities:[EuropeCities.KYIV, EuropeCities.PETROGRAD], points: 6, long:false },
	{id:38, game:Games.EUROPE, cities:[EuropeCities.ZURICH, EuropeCities.BUDAPEST], points: 6, long:false },
	{id:39, game:Games.EUROPE, cities:[EuropeCities.ZURICH, EuropeCities.BRINDISI], points: 6, long:false },
	{id:40, game:Games.EUROPE, cities:[EuropeCities.ZAGRAB, EuropeCities.BRINDISI], points: 6, long:false },
	{id:41, game:Games.EUROPE, cities:[EuropeCities.WARSZAWA, EuropeCities.SMOLENSK], points: 6, long:false },
	{id:42, game:Games.EUROPE, cities:[EuropeCities.SOFIA, EuropeCities.SMYRNA], points: 5, long:false },
	{id:43, game:Games.EUROPE, cities:[EuropeCities.ATHINA, EuropeCities.ANGORA], points: 5, long:false },
	{id:44, game:Games.EUROPE, cities:[EuropeCities.FRANKFURT, EuropeCities.KOBENHAVN], points: 5, long:false },
	{id:45, game:Games.EUROPE, cities:[EuropeCities.ERZURUM, EuropeCities.ROSTOV], points: 5, long:false },
	{id:46, game:Games.EUROPE, cities:[EuropeCities.BUDAPEST, EuropeCities.SOFIA], points: 5, long:false }
]

export const Tickets = {
    World: world,
    GreatLakes: greatlakes,
    Europe: europe
};