module.exports.WorldCities = {
    NOVOSIBIRSK:"Novosibirsk",
    DARWIN:"Darwin",
    MARSEILLE: "Marseille",
    AL_QAHIRA: "Al Qahira",
    VANCOUVER: "Vancouver",
    MIAMI: "Miami",
    BUENOS_AIRES: "Buenos Aires",
    MURMANSK: "Murmansk",
    TIKSI: "Tiksi",
    YAKUTSK: "Yakutsk",
    PETROPAVLOVSK: "Petropavlovsk",
    CARACAS: "Caracas",
    ATHINA: "Athina",
    MUMBAI: "Mumbai",
    BEIJING: "Beijing",
    MANILA: "Manila",
    HONOLULU: "Honolulu",
    PORT_MORESBY: "Port Moresby",
    NEW_YORK: "New York",
    MEXICO: "Mexico",
    DAR_ES_SALAAM: "Dar Es Salaam",
    TOKYO: "Tokyo",
    REYKJAVIK: "Reykjavik",
    BANGKOK: "Bangkok",
    JAKARTA: "Jakarta",
    SYDNEY: "Sydney",
    ANCHORAGE: "Anchorage",
    WINNIPEG: "Winnipeg",
    CAMBRIDGE_BAY: "Cambridge Bay",
    LOS_ANGELES: "Los Angeles",
    RIO_DE_JANEIRO: "Rio de Janeiro",
    HAMBURG: "Hamburg",
    LIMA: "Lima",
    TEHRAN: "Tehran",
    LAHORE: "Lahore",
    CASABLANCA: "Casablanca",
    LAGOS: "Lagos",
    LUANDA: "Luanda",
    DJIBOUTI: "Djibouti",
    VALPARAISO: "Valparaiso",
    HONG_KONG: "Hong Kong",
    EDINBURGH: "Edinburgh",
    MOSKVA: "Moskva",
    CHRISTCHURCH: "Christchurch",
    PERTH: "Perth",
    CAPE_TOWN: "Cape Town",
    TOAMASINA: "Toamasina"
}