module.exports.WorldCities = {
  NOVOSIBIRSK: { name: 'Novosibirsk', anchor: false },
  DARWIN: { name: 'Darwin', anchor: true },
  MARSEILLE: { name: 'Marseille', anchor: true },
  AL_QAHIRA: { name: 'Al Qahira', anchor: true },
  VANCOUVER: { name: 'Vancouver', anchor: true },
  MIAMI: { name: 'Miami', anchor: true },
  BUENOS_AIRES: { name: 'Buenos Aires', anchor: true },
  MURMANSK: { name: 'Murmansk', anchor: true },
  TIKSI: { name: 'Tiksi', anchor: true },
  YAKUTSK: { name: 'Yakutsk', anchor: false },
  PETROPAVLOVSK: { name: 'Petropavlovsk', anchor: true },
  CARACAS: { name: 'Caracas', anchor: true },
  ATHINA: { name: 'Athina', anchor: true },
  MUMBAI: { name: 'Mumbai', anchor: true },
  BEIJING: { name: 'Beijing', anchor: false },
  MANILA: { name: 'Manila', anchor: true },
  HONOLULU: { name: 'Honolulu', anchor: true },
  PORT_MORESBY: { name: 'Port Moresby', anchor: true },
  NEW_YORK: { name: 'New York', anchor: true },
  MEXICO: { name: 'Mexico', anchor: false },
  DAR_ES_SALAAM: { name: 'Dar Es Salaam', anchor: true },
  TOKYO: { name: 'Tokyo', anchor: true },
  REYKJAVIK: { name: 'Reykjavik', anchor: true },
  BANGKOK: { name: 'Bangkok', anchor: true },
  JAKARTA: { name: 'Jakarta', anchor: true },
  SYDNEY: { name: 'Sydney', anchor: true },
  ANCHORAGE: { name: 'Anchorage', anchor: true },
  WINNIPEG: { name: 'Winnipeg', anchor: false },
  CAMBRIDGE_BAY: { name: 'Cambridge Bay', anchor: true },
  LOS_ANGELES: { name: 'Los Angeles', anchor: true },
  RIO_DE_JANEIRO: { name: 'Rio de Janeiro', anchor: true },
  HAMBURG: { name: 'Hamburg', anchor: true },
  LIMA: { name: 'Lima', anchor: true },
  TEHRAN: { name: 'Tehran', anchor: false },
  LAHORE: { name: 'Lahore', anchor: false },
  CASABLANCA: { name: 'Casablanca', anchor: true },
  LAGOS: { name: 'Lagos', anchor: true },
  LUANDA: { name: 'Luanda', anchor: true },
  DJIBOUTI: { name: 'Djibouti', anchor: false },
  VALPARAISO: { name: 'Valparaiso', anchor: true },
  HONG_KONG: { name: 'Hong Kong', anchor: true },
  EDINBURGH: { name: 'Edinburgh', anchor: true },
  MOSKVA: { name: 'Moskva', anchor: false },
  CHRISTCHURCH: { name: 'Christchurch', anchor: true },
  PERTH: { name: 'Perth', anchor: true },
  CAPE_TOWN: { name: 'Cape Town', anchor: true },
  TOAMASINA: { name: 'Toamasina', anchor: true },
}
