module.exports.PennsylvaniaCities = {
  ALTOONA: { name: 'Altoona' },
  ALBANY: { name: 'Albany' },
  ALLENTOWN: { name: 'Allentown' },
  ATLANTIC_CITY: { name: 'Atlantic City' },
  BALTIMORE: { name: 'Baltimore' },
  BINGHAMTON: { name: 'Binghamton' },
  BUFFALO: { name: 'Buffalo' },
  CHAMBERSBURG: { name: 'Chambersburg' },
  COUDERSPORT: { name: 'Coudersport' },
  CUMBERLAND: { name: 'Cumberland' },
  DUBOIS: { name: 'Dubois' },
  ELMIRA: { name: 'Elmira' },
  ERIE: { name: 'Erie' },
  GETTYSBURG: { name: 'Gettysburg' },
  HARRISBURG: { name: 'Harrisburg' },
  JOHNSTOWN: { name: 'Johnstown' },
  LANCASTER: { name: 'Lancaster' },
  LEWISTON: { name: 'Lewiston' },
  MORGANTOWN: { name: 'Morgantown' },
  NEW_YORK: { name: 'New York' },
  OIL_CITY: { name: 'Oil City' },
  ONTARIO: { name: 'Ontario' },
  PHILADELPHIA: { name: 'Philadelphia' },
  PITTSBURGH: { name: 'Pittsburgh' },
  READING: { name: 'Reading' },
  ROCHESTER: { name: 'Rochester' },
  SCRANTON: { name: 'Scranton' },
  STROUDSBURG: { name: 'Stroudsburg' },
  SYRACUSE: { name: 'Syracuse' },
  TOWANDA: { name: 'Towanda' },
  WARREN: { name: 'Warren' },
  WHEELING: { name: 'Wheeling' },
  WILLIAMSPORT: { name: 'Williamsport' },
  YOUGSTOWN: { name: 'Youngstown' },
  YORK: { name: 'York' },
};
