import { PennsylvaniaCities } from './pennsylvania-cities';
import { GamesList } from '../games-list';
import { Types } from '../types';

export const pennsylvania = [
  {
    id: 1,
    game: GamesList.PENNSYLVANIA,
    type: Types.ROUTE,
    cities: [PennsylvaniaCities.ALTOONA, PennsylvaniaCities.BINGHAMTON],
    points: 9,
  },
  {
    id: 2,
    game: GamesList.PENNSYLVANIA,
    type: Types.ROUTE,
    cities: [PennsylvaniaCities.BALTIMORE, PennsylvaniaCities.ALBANY],
    points: 16,
  },
  {
    id: 3,
    game: GamesList.PENNSYLVANIA,
    type: Types.ROUTE,
    cities: [PennsylvaniaCities.BALTIMORE, PennsylvaniaCities.NEW_YORK],
    points: 10,
  },
  {
    id: 4,
    game: GamesList.PENNSYLVANIA,
    type: Types.ROUTE,
    cities: [PennsylvaniaCities.BALTIMORE, PennsylvaniaCities.PHILADELPHIA],
    points: 4,
  },
  {
    id: 5,
    game: GamesList.PENNSYLVANIA,
    type: Types.ROUTE,
    cities: [PennsylvaniaCities.BUFFALO, PennsylvaniaCities.BALTIMORE],
    points: 16,
  },
  {
    id: 6,
    game: GamesList.PENNSYLVANIA,
    type: Types.ROUTE,
    cities: [PennsylvaniaCities.BUFFALO, PennsylvaniaCities.HARRISBURG],
    points: 13,
  },
  {
    id: 7,
    game: GamesList.PENNSYLVANIA,
    type: Types.ROUTE,
    cities: [PennsylvaniaCities.BUFFALO, PennsylvaniaCities.JOHNSTOWN],
    points: 10,
  },
  {
    id: 8,
    game: GamesList.PENNSYLVANIA,
    type: Types.ROUTE,
    cities: [PennsylvaniaCities.BUFFALO, PennsylvaniaCities.NEW_YORK],
    points: 18,
  },
  {
    id: 9,
    game: GamesList.PENNSYLVANIA,
    type: Types.ROUTE,
    cities: [PennsylvaniaCities.BUFFALO, PennsylvaniaCities.PHILADELPHIA],
    points: 19,
  },
  {
    id: 10,
    game: GamesList.PENNSYLVANIA,
    type: Types.ROUTE,
    cities: [PennsylvaniaCities.CHAMBERSBURG, PennsylvaniaCities.SCRANTON],
    points: 8,
  },
  {
    id: 11,
    game: GamesList.PENNSYLVANIA,
    type: Types.ROUTE,
    cities: [PennsylvaniaCities.COUDERSPORT, PennsylvaniaCities.BINGHAMTON],
    points: 7,
  },
  {
    id: 12,
    game: GamesList.PENNSYLVANIA,
    type: Types.ROUTE,
    cities: [PennsylvaniaCities.CUMBERLAND, PennsylvaniaCities.HARRISBURG],
    points: 4,
  },
  {
    id: 13,
    game: GamesList.PENNSYLVANIA,
    type: Types.ROUTE,
    cities: [PennsylvaniaCities.DUBOIS, PennsylvaniaCities.CUMBERLAND],
    points: 6,
  },
  {
    id: 14,
    game: GamesList.PENNSYLVANIA,
    type: Types.ROUTE,
    cities: [PennsylvaniaCities.DUBOIS, PennsylvaniaCities.STROUDSBURG],
    points: 12,
  },
  {
    id: 15,
    game: GamesList.PENNSYLVANIA,
    type: Types.ROUTE,
    cities: [PennsylvaniaCities.ERIE, PennsylvaniaCities.ALBANY],
    points: 20,
  },
  {
    id: 16,
    game: GamesList.PENNSYLVANIA,
    type: Types.ROUTE,
    cities: [PennsylvaniaCities.ERIE, PennsylvaniaCities.ALTOONA],
    points: 8,
  },
  {
    id: 17,
    game: GamesList.PENNSYLVANIA,
    type: Types.ROUTE,
    cities: [PennsylvaniaCities.GETTYSBURG, PennsylvaniaCities.READING],
    points: 3,
  },
  {
    id: 18,
    game: GamesList.PENNSYLVANIA,
    type: Types.ROUTE,
    cities: [PennsylvaniaCities.HARRISBURG, PennsylvaniaCities.BALTIMORE],
    points: 3,
  },
  {
    id: 19,
    game: GamesList.PENNSYLVANIA,
    type: Types.ROUTE,
    cities: [PennsylvaniaCities.HARRISBURG, PennsylvaniaCities.NEW_YORK],
    points: 11,
  },
  {
    id: 20,
    game: GamesList.PENNSYLVANIA,
    type: Types.ROUTE,
    cities: [PennsylvaniaCities.HARRISBURG, PennsylvaniaCities.PHILADELPHIA],
    points: 6,
  },
  {
    id: 21,
    game: GamesList.PENNSYLVANIA,
    type: Types.ROUTE,
    cities: [PennsylvaniaCities.JOHNSTOWN, PennsylvaniaCities.ELMIRA],
    points: 10,
  },
  {
    id: 22,
    game: GamesList.PENNSYLVANIA,
    type: Types.ROUTE,
    cities: [PennsylvaniaCities.LEWISTON, PennsylvaniaCities.SYRACUSE],
    points: 9,
  },
  {
    id: 23,
    game: GamesList.PENNSYLVANIA,
    type: Types.ROUTE,
    cities: [PennsylvaniaCities.MORGANTOWN, PennsylvaniaCities.CHAMBERSBURG],
    points: 7,
  },
  {
    id: 24,
    game: GamesList.PENNSYLVANIA,
    type: Types.ROUTE,
    cities: [PennsylvaniaCities.MORGANTOWN, PennsylvaniaCities.WILLIAMSPORT],
    points: 13,
  },
  {
    id: 25,
    game: GamesList.PENNSYLVANIA,
    type: Types.ROUTE,
    cities: [PennsylvaniaCities.NEW_YORK, PennsylvaniaCities.ATLANTIC_CITY],
    points: 6,
  },
  {
    id: 26,
    game: GamesList.PENNSYLVANIA,
    type: Types.ROUTE,
    cities: [PennsylvaniaCities.OIL_CITY, PennsylvaniaCities.JOHNSTOWN],
    points: 6,
  },
  {
    id: 27,
    game: GamesList.PENNSYLVANIA,
    type: Types.ROUTE,
    cities: [PennsylvaniaCities.OIL_CITY, PennsylvaniaCities.SCRANTON],
    points: 14,
  },
  {
    id: 28,
    game: GamesList.PENNSYLVANIA,
    type: Types.ROUTE,
    cities: [PennsylvaniaCities.ONTARIO, PennsylvaniaCities.PITTSBURGH],
    points: 10,
  },
  {
    id: 29,
    game: GamesList.PENNSYLVANIA,
    type: Types.ROUTE,
    cities: [PennsylvaniaCities.ONTARIO, PennsylvaniaCities.SYRACUSE],
    points: 10,
  },
  {
    id: 30,
    game: GamesList.PENNSYLVANIA,
    type: Types.ROUTE,
    cities: [PennsylvaniaCities.ONTARIO, PennsylvaniaCities.WARREN],
    points: 5,
  },
  {
    id: 31,
    game: GamesList.PENNSYLVANIA,
    type: Types.ROUTE,
    cities: [PennsylvaniaCities.PHILADELPHIA, PennsylvaniaCities.ATLANTIC_CITY],
    points: 2,
  },
  {
    id: 32,
    game: GamesList.PENNSYLVANIA,
    type: Types.ROUTE,
    cities: [PennsylvaniaCities.PHILADELPHIA, PennsylvaniaCities.NEW_YORK],
    points: 6,
  },
  {
    id: 33,
    game: GamesList.PENNSYLVANIA,
    type: Types.ROUTE,
    cities: [PennsylvaniaCities.PITTSBURGH, PennsylvaniaCities.BALTIMORE],
    points: 13,
  },
  {
    id: 34,
    game: GamesList.PENNSYLVANIA,
    type: Types.ROUTE,
    cities: [PennsylvaniaCities.PITTSBURGH, PennsylvaniaCities.BUFFALO],
    points: 10,
  },
  {
    id: 35,
    game: GamesList.PENNSYLVANIA,
    type: Types.ROUTE,
    cities: [PennsylvaniaCities.PITTSBURGH, PennsylvaniaCities.HARRISBURG],
    points: 9,
  },
  {
    id: 36,
    game: GamesList.PENNSYLVANIA,
    type: Types.ROUTE,
    cities: [PennsylvaniaCities.PITTSBURGH, PennsylvaniaCities.NEW_YORK],
    points: 10,
  },
  {
    id: 37,
    game: GamesList.PENNSYLVANIA,
    type: Types.ROUTE,
    cities: [PennsylvaniaCities.PITTSBURGH, PennsylvaniaCities.PHILADELPHIA],
    points: 15,
  },
  {
    id: 38,
    game: GamesList.PENNSYLVANIA,
    type: Types.ROUTE,
    cities: [PennsylvaniaCities.ROCHESTER, PennsylvaniaCities.ELMIRA],
    points: 3,
  },
  {
    id: 39,
    game: GamesList.PENNSYLVANIA,
    type: Types.ROUTE,
    cities: [PennsylvaniaCities.ROCHESTER, PennsylvaniaCities.READING],
    points: 13,
  },
  {
    id: 40,
    game: GamesList.PENNSYLVANIA,
    type: Types.ROUTE,
    cities: [PennsylvaniaCities.SCRANTON, PennsylvaniaCities.ALLENTOWN],
    points: 3,
  },
  {
    id: 41,
    game: GamesList.PENNSYLVANIA,
    type: Types.ROUTE,
    cities: [PennsylvaniaCities.SYRACUSE, PennsylvaniaCities.ALLENTOWN],
    points: 8,
  },
  {
    id: 42,
    game: GamesList.PENNSYLVANIA,
    type: Types.ROUTE,
    cities: [PennsylvaniaCities.TOWANDA, PennsylvaniaCities.LANCASTER],
    points: 9,
  },
  {
    id: 43,
    game: GamesList.PENNSYLVANIA,
    type: Types.ROUTE,
    cities: [PennsylvaniaCities.WARREN, PennsylvaniaCities.YORK],
    points: 10,
  },
  {
    id: 44,
    game: GamesList.PENNSYLVANIA,
    type: Types.ROUTE,
    cities: [PennsylvaniaCities.WHEELING, PennsylvaniaCities.ALBANY],
    points: 22,
  },
  {
    id: 45,
    game: GamesList.PENNSYLVANIA,
    type: Types.ROUTE,
    cities: [PennsylvaniaCities.WHEELING, PennsylvaniaCities.ALLENTOWN],
    points: 15,
  },
  {
    id: 46,
    game: GamesList.PENNSYLVANIA,
    type: Types.ROUTE,
    cities: [PennsylvaniaCities.WHEELING, PennsylvaniaCities.ERIE],
    points: 9,
  },
  {
    id: 47,
    game: GamesList.PENNSYLVANIA,
    type: Types.ROUTE,
    cities: [PennsylvaniaCities.WILLIAMSPORT, PennsylvaniaCities.ALBANY],
    points: 10,
  },
  {
    id: 48,
    game: GamesList.PENNSYLVANIA,
    type: Types.ROUTE,
    cities: [PennsylvaniaCities.YOUGSTOWN, PennsylvaniaCities.MORGANTOWN],
    points: 7,
  },
  {
    id: 49,
    game: GamesList.PENNSYLVANIA,
    type: Types.ROUTE,
    cities: [PennsylvaniaCities.YOUGSTOWN, PennsylvaniaCities.ROCHESTER],
    points: 14,
  },
  {
    id: 50,
    game: GamesList.PENNSYLVANIA,
    type: Types.ROUTE,
    cities: [PennsylvaniaCities.YOUGSTOWN, PennsylvaniaCities.SCRANTON],
    points: 17,
  },
];
